apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.postgresql.username }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.postgresql.password }}"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
---
apiVersion: v1
kind: Service
metadata:
  name: kidsproject-postgres
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP