apiVersion: v1
kind: Secret
metadata:
  name: kidsproject-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  keycloak-client-secret: {{ .Values.keycloak.clientSecret }}
  postgresql-password: {{ .Values.postgresql.password }}
  rabbitmq-password: {{ .Values.rabbitmq.password }}